layout_spectrum: 0.4944201
typography_spectrum: 0.4114987
color:
  saturation: 0.8162303
  lightness: 0.1407091
  brandStrength: 0.344518
  rhythmicContrast: 0.1372494
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: I WANNA DANCE
